"""Score Claude's urgency labels against the blind hand-labels.

Reports exact agreement, Cohen's kappa, quadratic-weighted kappa (the tiers
are ordinal), within-one-tier agreement, the confusion matrix, per-tier
precision/recall, and every disagreement with the model's own reasoning.

    python scripts/score_labels.py      # -> eval/RESULTS.md, eval/results.json
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from datetime import date
from pathlib import Path

# Let `python scripts/<name>.py` import the project packages from a fresh clone.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from classifier.prompts import PROMPT_VERSION
from classifier.replay_classifier import DEFAULT_FIXTURE, load_fixture

TIERS = ["Low", "Medium", "High", "Critical"]  # ordinal, least -> most urgent
DEFAULT_SHEET = "eval/labels/label_sheet.csv"


def _normalise(label: str) -> str:
    cleaned = label.strip().capitalize()
    if cleaned not in TIERS:
        raise ValueError(f"unrecognised label {label!r}; expected one of {TIERS}")
    return cleaned


def cohens_kappa(pairs: list[tuple[str, str]], weights: str | None = None) -> float:
    """Cohen's kappa over TIERS; weights=None (nominal) or 'quadratic' (ordinal)."""
    k, n = len(TIERS), len(pairs)
    idx = {t: i for i, t in enumerate(TIERS)}
    observed = [[0.0] * k for _ in range(k)]
    for human, model in pairs:
        observed[idx[human]][idx[model]] += 1 / n
    row = [sum(r) for r in observed]
    col = [sum(observed[i][j] for i in range(k)) for j in range(k)]

    def w(i: int, j: int) -> float:
        if weights == "quadratic":
            return ((i - j) ** 2) / ((k - 1) ** 2)
        return 0.0 if i == j else 1.0

    num = sum(w(i, j) * observed[i][j] for i in range(k) for j in range(k))
    den = sum(w(i, j) * row[i] * col[j] for i in range(k) for j in range(k))
    return 1.0 if den == 0 else 1 - num / den


def score(sheet: str, fixture: str) -> dict:
    model = {r.service_request_id: r for r in load_fixture(fixture)}
    rows = []
    # utf-8-sig: Excel's "CSV UTF-8" save adds a BOM that would corrupt the first header.
    with open(sheet, encoding="utf-8-sig", newline="") as fh:
        for r in csv.DictReader(fh):
            if not r["human_label"].strip():
                raise SystemExit(f"item {r['item']} ({r['service_request_id']}) has no human_label yet")
            rec = model[r["service_request_id"]]
            rows.append({
                "item": int(r["item"]),
                "service_request_id": r["service_request_id"],
                "service_name": r["service_name"],
                "address": r["address"],
                "human": _normalise(r["human_label"]),
                "model": rec.urgency_label,
                "model_score": rec.urgency_score,
                "model_reasoning": rec.llm_reasoning,
                "notes": r.get("notes", "").strip(),
            })

    pairs = [(r["human"], r["model"]) for r in rows]
    n = len(pairs)
    rank = {t: i for i, t in enumerate(TIERS)}
    confusion = {h: {m: 0 for m in TIERS} for h in TIERS}
    for h, m in pairs:
        confusion[h][m] += 1

    per_tier = {}
    for t in TIERS:
        tp = confusion[t][t]
        predicted = sum(confusion[h][t] for h in TIERS)
        actual = sum(confusion[t].values())
        per_tier[t] = {
            "human_count": actual,
            "model_count": predicted,
            "precision": tp / predicted if predicted else None,
            "recall": tp / actual if actual else None,
        }

    disagreements = [r for r in rows if r["human"] != r["model"]]
    return {
        "n": n,
        "prompt_version": PROMPT_VERSION,
        "exact_agreement": sum(h == m for h, m in pairs) / n,
        "within_one_tier": sum(abs(rank[h] - rank[m]) <= 1 for h, m in pairs) / n,
        "cohens_kappa": cohens_kappa(pairs),
        "quadratic_weighted_kappa": cohens_kappa(pairs, "quadratic"),
        "model_more_urgent": sum(rank[m] > rank[h] for h, m in pairs),
        "model_less_urgent": sum(rank[m] < rank[h] for h, m in pairs),
        "confusion": confusion,
        "per_tier": per_tier,
        "disagreements": disagreements,
        "rows": rows,
    }


def _pct(x: float | None) -> str:
    return "—" if x is None else f"{x:.0%}"


def render_markdown(res: dict) -> str:
    lines = [
        "# Urgency classifier — agreement with blind hand-labels",
        "",
        f"_Generated by `scripts/score_labels.py` on {date.today().isoformat()}. "
        f"Prompt `{res['prompt_version']}`, model labels from the replay fixture. "
        "Do not edit by hand. Re-run `make score-labels`._",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Items hand-labelled | {res['n']} |",
        f"| Exact agreement | {_pct(res['exact_agreement'])} |",
        f"| Within one tier | {_pct(res['within_one_tier'])} |",
        f"| Cohen's kappa | {res['cohens_kappa']:.2f} |",
        f"| Quadratic-weighted kappa (ordinal) | {res['quadratic_weighted_kappa']:.2f} |",
        f"| Model more urgent than human | {res['model_more_urgent']} |",
        f"| Model less urgent than human | {res['model_less_urgent']} |",
        "",
        "## Confusion matrix",
        "",
        "Rows = human label, columns = model label.",
        "",
        "| human \\ model | " + " | ".join(TIERS) + " |",
        "|---|" + "---:|" * len(TIERS),
    ]
    for h in TIERS:
        lines.append(f"| **{h}** | " + " | ".join(str(res["confusion"][h][m]) for m in TIERS) + " |")
    lines += [
        "",
        "## Per tier",
        "",
        "| Tier | Human count | Model count | Precision | Recall |",
        "|---|---:|---:|---:|---:|",
    ]
    for t in TIERS:
        p = res["per_tier"][t]
        lines.append(f"| {t} | {p['human_count']} | {p['model_count']} | {_pct(p['precision'])} | {_pct(p['recall'])} |")
    lines += ["", f"## Every disagreement ({len(res['disagreements'])})", ""]
    if res["disagreements"]:
        lines += [
            "| # | Category | Human | Model (conf.) | Model's reasoning | Labeler note |",
            "|---:|---|---|---|---|---|",
        ]
        for r in res["disagreements"]:
            reasoning = r["model_reasoning"].replace("|", "\\|")
            note = r["notes"].replace("|", "\\|")
            lines.append(
                f"| {r['item']} | {r['service_name']} | {r['human']} | "
                f"{r['model']} ({r['model_score']:.2f}) | {reasoning} | {note} |"
            )
    else:
        lines.append("None.")
    lines += [
        "",
        "## Error analysis",
        "",
        "[TKTK: written by hand after reading the disagreements above. Which "
        "categories drive them, whether the model is systematically over- or "
        "under-urgent, and what a v2 prompt would change.]",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--sheet", default=DEFAULT_SHEET)
    parser.add_argument("--fixture", default=DEFAULT_FIXTURE)
    parser.add_argument("--out-dir", default="eval")
    args = parser.parse_args()

    res = score(args.sheet, args.fixture)
    out = Path(args.out_dir)
    (out / "results.json").write_text(json.dumps(res, indent=2, default=str) + "\n", encoding="utf-8")
    md_path = out / "RESULTS.md"
    new_md = render_markdown(res)
    if md_path.exists():
        # Keep a hand-written error analysis across re-runs.
        old = md_path.read_text(encoding="utf-8")
        marker = "## Error analysis"
        if marker in old and "[TKTK" not in old.split(marker, 1)[1]:
            new_md = new_md.split(marker, 1)[0] + marker + old.split(marker, 1)[1]
    md_path.write_text(new_md, encoding="utf-8")
    print(
        f"n={res['n']}  exact={res['exact_agreement']:.0%}  within-one={res['within_one_tier']:.0%}  "
        f"kappa={res['cohens_kappa']:.2f}  qwk={res['quadratic_weighted_kappa']:.2f}  -> {md_path}"
    )


if __name__ == "__main__":
    main()
